name: man_domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^2.4.3
  mocktail: ^1.0.4
  state_notifier: ^1.0.0
  goal_domain:
    path: '../../goal/goal_domain'
  # path: ^1.8.0
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
