targets:
  $default:
    builders:
      freezed:
        options:
          union_key: type
          union_value_case: snake
      json_serializable:
        options:
          explicit_to_json: false
