name: goals_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  state_notifier: ^1.0.0
  freezed_annotation: ^2.4.3
  json_annotation: ^4.9.0
  uuid: ^4.4.0
  flutter_state_notifier: ^1.0.0
  provider: ^6.1.2
  man_domain:
    path: 'packages/man/man_domain'
  goal_domain:
    path: 'packages/goal/goal_domain'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
    